version: "2"

services:
  wedding:
    build: .
    container_name: wedding
    restart: always
    environment:
      - VIRTUAL_HOST=catherine-et-arthur.ca
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=catherine-et-arthur.ca
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: arthur_default
