version: "2"

services:
  wedding:
    build: .
    container_name: wedding
    restart: always
    environment:
      - VIRTUAL_HOST=mariage.juchereau.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mariage.juchereau.com
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
networks:
  default:
    external:
      name: arthur_default
